export const EDIT_FORM = "EDIT_FORM";
export const FETCH_USER_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USERS_FAILURE";
export const HIDE_MODAL = "HIDE_MODAL";
